version: "3.9"
services:
  checkout:
    build: 
      context: .
      dockerfile: checkout.dockerfile
    image: checkout:1.0
  get-user:
    build: 
      context: .
      dockerfile: get-user.dockerfile
    image: get-user:1.0
  post-user:
    build: 
      context: .
      dockerfile: post-user.dockerfile
    image: post-user:1.0
  put-user:
    build: 
      context: .
      dockerfile: put-user.dockerfile
    image: put-user:1.0
  delete-user:
    build: 
      context: .
      dockerfile: delete-user.dockerfile
    image: delete-user:1.0
  get-book:
    build: 
      context: .
      dockerfile: get-book.dockerfile
    image: get-book:1.0
  post-book:
    build: 
      context: .
      dockerfile: post-book.dockerfile
    image: post-book:1.0
  put-book:
    build: 
      context: .
      dockerfile: put-book.dockerfile
    image: put-book:1.0
  delete-book:
    build: 
      context: .
      dockerfile: delete-book.dockerfile
    image: delete-book:1.0